### ISSUE TITLE
User Stories 

### ISSUE THREAD

**Issue by bytelisa** [bytelisa/StudyPal#1]
Creato issue come esercizio per il corso, come aveva detto il professore :)
Fai lo stesso anche tu @valejin 
[User stories con Vale.pdf](https://github.com/bytelisa/StudyPal/files/14550927/User.stories.con.Vale.pdf)

**Comment by bytelisa** [comment]
Chiudo issue

**Comment by valejin** [comment]
Carico i miei User Stories scritti dal punto di vista dello studente.
[User stories VALE.pdf](https://github.com/bytelisa/StudyPal/files/14550970/User.stories.VALE.pdf)
